version: '1.0.0'
module: github.com/go-teal/demo
connections:
  - name: default
    type: duckdb
    config:
      path: ./store/db_file.duckdb            
      extensions:
        - postgres
        - httpfs         
  - name: test_pg
    type: postgres
    config:
      host: 127.0.0.1
      port: 5432
      user: postgres
      password: "hLH1i9mcAX"
      database: teal
